### ISSUE TITLE
Error in building the package

### ISSUE THREAD

**Issue by jellypuno** [zowe/zowe-explorer-ftp-extension#5]
I am following the [Build This Extension](https://github.com/zowe/zowe-explorer-ftp-extension#build-this-extension) instructions and I encountered this error. I installed eslint and prettier manually but it is still happening. No idea why. I just disabled `npm run lint` when building the package.

![Capture](https://user-images.githubusercontent.com/45042840/84631289-6b5d9a00-aeed-11ea-9afc-24c1abbf228e.PNG)

**Comment by phaumer** [comment]
@jellypuno can you review the linked PR?
